<div class="attorna-page-title-wrap  attorna-style-custom attorna-center-align">
    <div class=attorna-header-transparent-substitute></div>
    <div class=attorna-page-title-overlay></div>
    <div class="attorna-page-title-container attorna-container">
        <div class="attorna-page-title-content attorna-item-pdlr" style="padding-top: 150px ;padding-bottom: 150px ;">
            <h1 class="attorna-page-title" style="font-size: 57px ;text-transform: none ;">
                <?=strtoupper($this->modelo->SerTitle);?></h1>
        </div>
    </div>
</div>

<div class=attorna-page-wrapper id=attorna-page-wrapper>
    <div class=gdlr-core-page-builder-body>
        <div class="gdlr-core-pbf-sidebar-wrapper ">
            <div
                class="gdlr-core-pbf-sidebar-container gdlr-core-line-height-0 clearfix gdlr-core-js gdlr-core-container">
                <div
                    class="gdlr-core-pbf-sidebar-content  gdlr-core-column-40 gdlr-core-pbf-sidebar-padding gdlr-core-line-height gdlr-core-column-extend-right">
                    <div class=gdlr-core-pbf-background-wrap style="background-color: #f7f7f7 ;"></div>
                    <div class=gdlr-core-pbf-sidebar-content-inner>
                        <div class=gdlr-core-pbf-element>
                            <div class="gdlr-core-blog-item gdlr-core-item-pdb clearfix  gdlr-core-style-blog-full-with-frame"
                                style="padding-bottom: 40px ;">
                                <div class="gdlr-core-blog-item-holder gdlr-core-js-2 clearfix" data-layout=fitrows>
                                    <div
                                        class="gdlr-core-item-list gdlr-core-blog-full gdlr-core-style-3  gdlr-core-item-mglr gdlr-core-style-left gdlr-core-with-thumbnail">
                                        <div
                                            class="gdlr-core-blog-thumbnail gdlr-core-media-image  gdlr-core-opacity-on-hover gdlr-core-zoom-on-hover">
                                            <a href=#><img
                                                    src="<?=Com_Helper_Url::getInstance()->getUploads();?>/Image/<?=$this->modelo->SerImage?>"
                                                    alt width=900 height=500 title=patrick-fore-379185-unsplash>

                                            </a>
                                        </div>
                                        <div class="gdlr-core-blog-full-frame gdlr-core-skin-e-background"
                                            style="padding-top: 50px;padding-bottom: 50px;">
                                            <div class="gdlr-core-blog-full-head clearfix">
                                                <h3 class="gdlr-core-blog-title gdlr-core-skin-title"
                                                    style="font-size: 27px ;font-weight: 700 ;letter-spacing: 0px ;"><a
                                                        href=#><?=$this->modelo->SerTitle;?></a></h3>
                                            </div>
                                            <div class=gdlr-core-blog-content><?=$this->modelo->SerDescription;?></div>
                                        </div>
                                    </div>

                                </div>

                            </div>
                        </div>
                    </div>
                </div>
                <div class="gdlr-core-pbf-sidebar-left gdlr-core-column-extend-left  attorna-sidebar-area gdlr-core-column-20 gdlr-core-pbf-sidebar-padding  gdlr-core-line-height"
                    style="padding: 80px 30px 30px 0px;">
                    <div class=gdlr-core-pbf-background-wrap style="background-color: #f7f7f7 ;"></div>
                    <div class="gdlr-core-sidebar-item gdlr-core-item-pdlr">
                        <div id=gdlr-core-custom-menu-widget-5
                            class="widget widget_gdlr-core-custom-menu-widget attorna-widget">
                            <h3 class="attorna-widget-title">
                                <?=Texts_Helper_Text::getInstance()->get($this->lan, "TitleListAreas")->TxtDescription;?>
                            </h3><span class=clear></span>
                            <div class=menu-practice-areas-container>
                                <ul id=menu-practice-areas
                                    class="gdlr-core-custom-menu-widget gdlr-core-menu-style-list">
                                    <?php Services_Widget_Services::getInstance()->setLan($this->lan)->renderList();?>
                                </ul>
                            </div>
                        </div>
                        <div id="text-9" class="widget widget_text attorna-widget">
                            <div class="textwidget">
                                <p>
                                    <span class="gdlr-core-space-shortcode" style="margin-top: 15px ;"></span>
                                </p>
                                <div class="gdlr-core-widget-box-shortcode "
                                    style="color: #b8b8b8 ;padding: 50px 37px 30px 43px;border-radius: 3px;-moz-border-radius: 3px;-webkit-border-radius: 3px;background-image: url(https://demo.goodlayers.com/attorna/wp-content/uploads/2019/02/sidebar-contact-bg.jpg) ;border: 0px solid #293b6d ;">
                                    <h3 class="gdlr-core-widget-box-shortcode-title" style="color: #b1976b ;">
                                        <?=Texts_Helper_Text::getInstance()->get($this->lan, "HomeTitleSuscribe")->TxtDescription;?>
                                    </h3>
                                    <div class="gdlr-core-widget-box-shortcode-content">
                                        <p><?=Texts_Helper_Text::getInstance()->get($this->lan, "HomeSubTitleSuscribe")->TxtDescription;?>
                                            </span></p>
                                        <p><i class="fa fa-envelope-open-o"
                                                style="font-size: 14px ;color: #b1976b ;margin-right: 10px ;"></i>
                                            <?=Texts_Helper_Text::getInstance()->get($this->lan, "ContactEmail")->TxtDescription;?><span
                                                class="gdlr-core-space-shortcode" style="margin-top: 7px ;"></span><i
                                                class="icon_clock_alt"
                                                style="font-size: 15px ;color: #b1976b ;margin-right: 10px ;"></i>
                                            <?=Texts_Helper_Text::getInstance()->get($this->lan, "Schedule")->TxtDescription;?>
                                        </p>
                                    </div>
                                </div><span class="gdlr-core-space-shortcode" style="margin-top: 20px ;"></span>
                                <p></p>
                                <a class="gdlr-core-button gdlr-core-button-shortcode  gdlr-core-button-solid gdlr-core-button-no-border gdlr-core-button-full-width"
                                    href="https://www.nuskin.com/content/dam/AEsoP/Library/onDemand/Truman%20Hunt%20Convention%20Presentation%20Flip%20Chart.pdf"
                                    target="_blank"
                                    style="display: none;font-size: 14px ;letter-spacing: 0px ;padding: 19px 29px 20px;text-transform: none ;border-radius: 3px;-moz-border-radius: 3px;-webkit-border-radius: 3px;background: #b1976b ;"><i
                                        class="gdlr-core-pos-left fa fa-file-pdf-o" style="color: #ffffff ;"></i><span
                                        class="gdlr-core-content">Firm’s Presentation</span></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>