<div class="attorna-page-title-wrap  attorna-style-custom attorna-center-align">
    <div class=attorna-header-transparent-substitute></div>
    <div class=attorna-page-title-overlay></div>
    <div class="attorna-page-title-container attorna-container">
        <div class="attorna-page-title-content attorna-item-pdlr" style="padding-top: 150px ;padding-bottom: 150px ;">
            <h1 class="attorna-page-title" style="font-size: 57px ;text-transform: none ;">
                <?=strtoupper($this->events->EveTitle);?></h1>
        </div>
    </div>
</div>
<div class=attorna-page-wrapper id=attorna-page-wrapper>
    <div class=gdlr-core-page-builder-body>
        <div class="gdlr-core-pbf-sidebar-wrapper ">
            <div
                class="gdlr-core-pbf-sidebar-container gdlr-core-line-height-0 clearfix gdlr-core-js gdlr-core-container">
                <div class="gdlr-core-pbf-sidebar-content  gdlr-core-column-40 gdlr-core-pbf-sidebar-padding gdlr-core-line-height gdlr-core-column-extend-left"
                    style="padding: 60px 10px 30px 0px;">
                    <div class=gdlr-core-pbf-background-wrap style="background-color: #f7f7f7 ;"></div>
                    <div class=gdlr-core-pbf-sidebar-content-inner>
                        <div class=gdlr-core-pbf-element>
                            <div class="gdlr-core-blog-item gdlr-core-item-pdb clearfix  gdlr-core-style-blog-full-with-frame"
                                style="padding-bottom: 40px ;">
                                <div class="gdlr-core-blog-item-holder gdlr-core-js-2 clearfix" data-layout=fitrows>
                                    <div
                                        class="gdlr-core-item-list gdlr-core-blog-full gdlr-core-style-3  gdlr-core-item-mglr gdlr-core-style-left gdlr-core-with-thumbnail">
                                        <div
                                            class="gdlr-core-blog-thumbnail gdlr-core-media-image  gdlr-core-opacity-on-hover gdlr-core-zoom-on-hover">
                                            <a href=#><img
                                                    src="<?=Com_Helper_Url::getInstance()->getUploads();?>/Image/<?PHP echo $this->events->EveImage; ?>"
                                                    alt width=900 height=500 title=patrick-fore-379185-unsplash>

                                            </a>
                                        </div>
                                        <div class="gdlr-core-blog-full-frame gdlr-core-skin-e-background"
                                            style="padding-top: 50px;padding-bottom: 50px;">
                                            <div class="gdlr-core-blog-full-head clearfix">
                                                <h3 class="gdlr-core-blog-title gdlr-core-skin-title"
                                                    style="font-size: 27px ;font-weight: 700 ;letter-spacing: 0px ;"><a
                                                        href=#><?=($this->events->EveTitle);?></a></h3>
                                            </div>
                                            <div class=gdlr-core-blog-content><?=$this->events->EveContent;?></div>
                                            <div class="gdlr-core-blog-info-wrapper gdlr-core-skin-divider"><span
                                                    class="gdlr-core-blog-info gdlr-core-blog-info-font gdlr-core-skin-caption gdlr-core-blog-info-date"><span
                                                        class=gdlr-core-blog-info-sep>•</span><span
                                                        class=gdlr-core-head><i class=icon_clock_alt></i></span><a
                                                        href=#><?=$this->events->EveDate;?></a></span><span
                                                    class="gdlr-core-blog-info gdlr-core-blog-info-font gdlr-core-skin-caption gdlr-core-blog-info-author"><span
                                                        class=gdlr-core-head><i
                                                            class=icon_documents_alt></i></span></span><span
                                                    class="gdlr-core-blog-info gdlr-core-blog-info-font gdlr-core-skin-caption gdlr-core-blog-info-tag"><span
                                                        class=gdlr-core-blog-info-sep>•</span><span
                                                        class=gdlr-core-head><i class=icon_tags_alt></i></span><a href=#
                                                        rel=tag><?=CatEvents_Helper_Category::getInstance()->getId($this->lan, $this->events->EveCatId)->CatName;?></a>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                            </div>
                        </div>
                    </div>
                </div>
                <div class="gdlr-core-pbf-sidebar-right gdlr-core-column-extend-right  attorna-sidebar-area gdlr-core-column-20 gdlr-core-pbf-sidebar-padding  gdlr-core-line-height"
                    style="padding: 80px 0px 30px 0px;">
                    <div class=gdlr-core-pbf-background-wrap style="background-color: #f7f7f7 ;"></div>
                    <div class="gdlr-core-sidebar-item gdlr-core-item-pdlr">
                        <div id=gdlr-core-recent-post-widget-2
                            class="widget widget_gdlr-core-recent-post-widget attorna-widget">
                            <h3 class="attorna-widget-title">Artiulos Recientes</h3><span class=clear></span>
                            <div class="gdlr-core-recent-post-widget-wrap gdlr-core-style-1">
                                <?php Events_Widget_Recientes::getInstance()->setLan($this->lan)->setLimit(5)->renderInNew();?>

                            </div>
                        </div>

                        <div id=tag_cloud-1 class="widget widget_tag_cloud attorna-widget">
                            <h3 class="attorna-widget-title">Tag Cloud</h3>
                            <span class=clear></span>
                            <div class=tagcloud>
                                <?php foreach ($this->category as $new) {?>
                                <a href="<?PHP echo Com_Helper_Url::getInstance()->generateUrl($this->lan->LanCode, "
                                    events/" . $new->CatId); ?>" class="tag-cloud-link tag-link-86 tag-link-position-1"
                                    style="font-size: 18.5pt;" aria-label="Antitrust (3 items)"><?=$new->CatName;?></a>
                                <?php }?>

                            </div>
                        </div>


                    </div>
                </div>
            </div>
        </div>
        <div class=gdlr-core-pbf-section>
            <div class="gdlr-core-pbf-section-container gdlr-core-container clearfix">
                <div class="gdlr-core-pbf-column gdlr-core-column-12 gdlr-core-column-first">
                    <div class="gdlr-core-pbf-column-content-margin gdlr-core-js ">
                        <div class="gdlr-core-pbf-column-content clearfix gdlr-core-js "></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>