<div class=" ">
    <div class=attorna-page-wrapper id=attorna-page-wrapper>
        <div class=gdlr-core-page-builder-body>
            <div class="gdlr-core-pbf-wrapper " style="padding: 85px 0px 60px 0px;">
                <div class=gdlr-core-pbf-background-wrap></div>
                <div class="gdlr-core-pbf-wrapper-content gdlr-core-js ">
                    <div class="gdlr-core-pbf-wrapper-container clearfix gdlr-core-container">
                        <div class="gdlr-core-pbf-column gdlr-core-column-20 gdlr-core-column-first">
                            <div class="gdlr-core-pbf-column-content-margin gdlr-core-js "
                                style="padding: 0px 0px 0px 0px;">
                                <div class="gdlr-core-pbf-column-content clearfix gdlr-core-js ">
                                    <div class=gdlr-core-pbf-element>
                                        <div class="gdlr-core-image-item gdlr-core-item-pdlr gdlr-core-item-pdb  gdlr-core-center-align"
                                            style="padding-bottom: 0px ;">
                                            <div class="gdlr-core-image-item-wrap gdlr-core-media-image  gdlr-core-image-item-style-round"
                                                style="border-width: 0px;margin: 0px 0px 37px 0px;"><img
                                                    src="<?=Com_Helper_Url::getInstance()->getUploads();?>/Image/<?=$this->team->TeamImage?>"
                                                    alt width=599 height=551 title=James></div>
                                        </div>
                                    </div>
                                    <div class=gdlr-core-pbf-element>
                                        <div class="gdlr-core-title-item gdlr-core-item-pdb clearfix  gdlr-core-left-align gdlr-core-title-item-caption-bottom gdlr-core-item-pdlr"
                                            style="padding-bottom: 25px ;">
                                            <div class="gdlr-core-title-item-title-wrap ">
                                                <h3 class="gdlr-core-title-item-title gdlr-core-skin-title "
                                                    style="font-size: 22px ;font-weight: 700 ;letter-spacing: 0px ;text-transform: none ;">
                                                    <?=$this->team->TeamNombre?><span
                                                        class="gdlr-core-title-item-title-divider gdlr-core-skin-divider"></span>
                                                </h3>
                                            </div><span
                                                class="gdlr-core-title-item-caption gdlr-core-info-font gdlr-core-skin-caption"
                                                style="font-style: normal ;margin-top: 5px ;"><?=$this->team->TeamCargo?></span>
                                        </div>
                                    </div>
                                    <div class=gdlr-core-pbf-element>
                                        <div class="gdlr-core-text-box-item gdlr-core-item-pdlr gdlr-core-item-pdb gdlr-core-left-align gdlr-core-no-p-space"
                                            style="padding-bottom: 10px ;">
                                            <div class=gdlr-core-text-box-item-content
                                                style="font-size: 16px ;text-transform: none ;color: #323232 ;">
                                                <p><span
                                                        style="font-weight: bold; margin-right: 10px;"><?=Texts_Helper_Text::getInstance()->get($this->lan, "ProfileEmail")->TxtDescription;?></span>
                                                    <?=$this->team->TeamEmail?></p>
                                            </div>
                                        </div>
                                    </div>
                                    <div class=gdlr-core-pbf-element>
                                        <div class="gdlr-core-text-box-item gdlr-core-item-pdlr gdlr-core-item-pdb gdlr-core-left-align"
                                            style="padding-bottom: 0px ;">
                                            <div class=gdlr-core-text-box-item-content
                                                style="font-size: 16px ;text-transform: none ;color: #323232 ;">
                                                <p><span
                                                        style="font-weight: bold; margin-right: 10px;"><?=Texts_Helper_Text::getInstance()->get($this->lan, "ProfilePhone")->TxtDescription;?></span>
                                                    <?=$this->team->TeamTelefono?></p>
                                            </div>
                                        </div>
                                    </div>
                                    <div class=gdlr-core-pbf-element>
                                        <div
                                            class="gdlr-core-social-network-item gdlr-core-item-pdb  gdlr-core-left-align gdlr-core-item-pdlr">
                                            <a href=" <?=$this->team->TeamLinkedin?>" target=_blank
                                                class=gdlr-core-social-network-icon title=linkedin
                                                style="font-size: 18px ;margin-left: 0px ;"><i
                                                    class="fa fa-linkedin"></i></a>
                                        </div>
                                    </div>
                                    <!-- VICARD <div class=gdlr-core-pbf-element>
                                    <div class="gdlr-core-button-item gdlr-core-item-pdlr gdlr-core-item-pdb gdlr-core-left-align"><a class="gdlr-core-button  gdlr-core-button-transparent gdlr-core-button-no-border" href=# style="font-size: 12px ;font-weight: 600 ;letter-spacing: 3px ;color: #b1976b ;padding: 0px 0px 0px 0px;"><span class=gdlr-core-content >Download VCard</span><i class="gdlr-core-pos-right fa fa-long-arrow-right" style="font-size: 18px ;color: #b1976b ;"  ></i></a></div>
                                </div> -->
                                </div>
                            </div>
                        </div>
                        <div class="gdlr-core-pbf-column gdlr-core-column-40">
                            <div class="gdlr-core-pbf-column-content-margin gdlr-core-js "
                                style="padding: 0px 0px 0px 0px;">
                                <div class="gdlr-core-pbf-column-content clearfix gdlr-core-js ">
                                    <div class=gdlr-core-pbf-element>
                                        <div class="gdlr-core-title-item gdlr-core-item-pdb clearfix  gdlr-core-left-align gdlr-core-title-item-caption-bottom gdlr-core-item-pdlr"
                                            style="padding-bottom: 25px ;">
                                            <div class="gdlr-core-title-item-title-wrap ">
                                                <h2 class="gdlr-core-title-item-title gdlr-core-skin-title "
                                                    style="font-size: 15px ;font-weight: 700 ;letter-spacing: 4px ;">
                                                    <?=Texts_Helper_Text::getInstance()->get($this->lan, "ProfileBio")->TxtDescription;?><span
                                                        class="gdlr-core-title-item-title-divider gdlr-core-skin-divider"></span>
                                                </h2>
                                            </div>
                                        </div>
                                    </div>
                                    <div class=gdlr-core-pbf-element>
                                        <div class="gdlr-core-text-box-item gdlr-core-item-pdlr gdlr-core-item-pdb gdlr-core-left-align"
                                            style="padding-bottom: 0px ;">
                                            <div class=gdlr-core-text-box-item-content style="text-transform: none ;">
                                                <?=$this->team->TeamContenido?>
                                            </div>
                                        </div>
                                    </div>

                                    <div class=gdlr-core-pbf-element>
                                        <div class="gdlr-core-title-item gdlr-core-item-pdb clearfix  gdlr-core-left-align gdlr-core-title-item-caption-top gdlr-core-item-pdlr"
                                            style="padding-bottom: 20px ;">
                                            <div class="gdlr-core-title-item-title-wrap ">
                                                <h3 class="gdlr-core-title-item-title gdlr-core-skin-title "
                                                    style="font-size: 15px ;font-weight: 700 ;letter-spacing: 4px ;">
                                                    <?=Texts_Helper_Text::getInstance()->get($this->lan, "ProfileLanguage")->TxtDescription;?><span
                                                        class="gdlr-core-title-item-title-divider gdlr-core-skin-divider"></span>
                                                </h3>
                                            </div>
                                        </div>
                                    </div>
                                    <div class=gdlr-core-pbf-element>
                                        <div
                                            class="gdlr-core-icon-list-item gdlr-core-item-pdlr gdlr-core-item-pdb clearfix  gdlr-core-left-align">
                                            <p> <?=$this->team->TeamSkills?></p>
                                        </div>
                                    </div>
                                    <div class=gdlr-core-pbf-element>
                                        <div class="gdlr-core-divider-item gdlr-core-divider-item-normal gdlr-core-item-pdlr gdlr-core-center-align"
                                            style="margin-bottom: 45px ;">
                                            <div class="gdlr-core-divider-line gdlr-core-skin-divider"></div>
                                        </div>
                                    </div>
                                    <div class=gdlr-core-pbf-element>
                                        <div
                                            class="gdlr-core-title-item gdlr-core-item-pdb clearfix  gdlr-core-left-align gdlr-core-title-item-caption-top gdlr-core-item-pdlr">
                                            <div class="gdlr-core-title-item-title-wrap ">
                                                <h3 class="gdlr-core-title-item-title gdlr-core-skin-title "
                                                    style="font-size: 15px ;font-weight: 700 ;letter-spacing: 4px ;">
                                                    <?=Texts_Helper_Text::getInstance()->get($this->lan, "ProfileStudies")->TxtDescription;?><span
                                                        class="gdlr-core-title-item-title-divider gdlr-core-skin-divider"></span>
                                                </h3>
                                            </div>
                                        </div>
                                    </div>

                                    <?php foreach (json_decode($this->skills, true) as $key => $value) {?>
                                    <div class=gdlr-core-pbf-element>
                                        <div class="gdlr-core-text-box-item gdlr-core-item-pdlr gdlr-core-item-pdb gdlr-core-left-align"
                                            style="padding-bottom: 0px ;">
                                            <div class=gdlr-core-text-box-item-content
                                                style="font-size: 16px ;text-transform: none ;">
                                                <p><?=$value["name"]?></p>
                                            </div>
                                        </div>
                                    </div>
                                    <div class=gdlr-core-pbf-element>
                                        <div class="gdlr-core-divider-item gdlr-core-divider-item-normal gdlr-core-item-pdlr gdlr-core-left-align"
                                            style="margin-bottom: 20px ;">
                                            <div class=gdlr-core-divider-container style="max-width: 22px ;">
                                                <div class="gdlr-core-divider-line gdlr-core-skin-divider"
                                                    style="border-color: #b1976b ;border-bottom-width: 2px ;"></div>
                                            </div>
                                        </div>
                                    </div>
                                    <?php }?>


                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>