<!DOCTYPE html>
<html lang=en-US class=no-js>


<head>
    <meta charset="utf-8">
    <meta name="description" content="<?=$this->page->PagDescription;?>">
    <meta name="viewport" content="width=device-width, initial-scale=1, minimal-ui">

    <!-- Google Authorship and Publisher Markup -->
    <link rel="author" href="http://villegasaldazosa.com/">
    <link rel="publisher" href="http://villegasaldazosa.com/" />

    <!-- Schema.org markup for Google+ -->
    <meta itemprop="name" content="<?=$this->page->PagName;?>">
    <meta itemprop="description" content="<?=$this->page->PagDescription;?>">
    <meta itemprop="image"
        content="<?=Com_Helper_Url::getInstance()->getUploads();?>/Image/<?php echo $this->page->PagImage; ?>">

    <!-- Twitter Card data -->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="@publisher_handle">
    <meta name="twitter:title" content="<?=$this->page->PagName;?>">
    <meta name="twitter:description" content="<?=$this->page->PagDescription;?>">
    <meta name="twitter:creator" content="@VillegasAldazosa">
    <!-- Imagen de sumario de Twitter debe al menos tener 280x150px -->
    <meta name="twitter:image:src"
        content="<?=Com_Helper_Url::getInstance()->getUploads();?>/Image/<?php echo $this->page->PagImage; ?>">

    <!-- Open Graph data -->
    <meta property="og:title" content="<?=$this->page->PagName;?>" />
    <meta property="og:type" content="article" />
    <meta property="og:url" content=" http://www.villegasaldazosa.com/" />
    <meta property="og:image"
        content="<?=Com_Helper_Url::getInstance()->getUploads();?>/Image/<?php echo $this->page->PagImage; ?>" />
    <meta property="og:description" content="<?=$this->page->PagDescription;?>" />
    <meta property="og:site_name" content="Villegas Aldazosa" />

    <title><?=Configurations_Helper_Configuration::getInstance()->getKey('PAGE_TITLE');?></title>


    <link rel="apple-touch-icon" sizes="180x180"
        href="<?PHP echo Com_Helper_Url::getInstance()->getImage(); ?>/Public/favicons/apple-touch-icon.png">
    <link rel="icon" type="image/png"
        href="<?PHP echo Com_Helper_Url::getInstance()->getImage(); ?>/Public/favicons/favicon-32x32.png" sizes="32x32">
    <link rel="icon" type="image/png"
        href="<?PHP echo Com_Helper_Url::getInstance()->getImage(); ?>/Public/favicons/favicon-16x16.png" sizes="16x16">

    <link rel="mask-icon"
        href="<?PHP echo Com_Helper_Url::getInstance()->getImage(); ?>/Public/favicons/safari-pinned-tab.svg"
        color="#5bbad5">
    <link rel="shortcut icon"
        href="<?PHP echo Com_Helper_Url::getInstance()->getImage(); ?>/Public/favicons/favicon.ico"
        type="image/x-icon" />




    <?PHP

Com_Helper_Style::getInstance()
    ->addFile("Public/plugins/goodlayers-core/plugins/combine/style.css")
    ->addFile("Public/plugins/goodlayers-core/include/css/page-builder.css")
    ->addFile("Public/plugins/revslider/public/assets/css/settings.css")
    ->addFile("Public/style-core.css")
    ->addFile("Public/attorna-style-custom.css")
    ->addFile("Public/plugins/revslider/public/assets/fonts/font-awesome/css/font-awesome.css")

;
echo Com_Helper_Style::getInstance();
?>
    <link rel=stylesheet
        href='https://fonts.googleapis.com/css?family=Poppins%3A100%2C100italic%2C200%2C200italic%2C300%2C300italic%2Cregular%2Citalic%2C500%2C500italic%2C600%2C600italic%2C700%2C700italic%2C800%2C800italic%2C900%2C900italic%7CMontserrat%3A100%2C100italic%2C200%2C200italic%2C300%2C300italic%2Cregular%2Citalic%2C500%2C500italic%2C600%2C600italic%2C700%2C700italic%2C800%2C800italic%2C900%2C900italic%7CMerriweather%3A300%2C300italic%2Cregular%2Citalic%2C700%2C700italic%2C900%2C900italic&amp;subset=latin%2Clatin-ext%2Cdevanagari%2Ccyrillic-ext%2Cvietnamese%2Ccyrillic&amp;'
        type=text/css media=all>

</head>

<body
    class="home page-template-default page page-id-2039 gdlr-core-body woocommerce-no-js attorna-body attorna-body-front attorna-full  attorna-with-sticky-navigation  attorna-blockquote-style-1 gdlr-core-link-to-lightbox"
    data-home-url=index.html>
    <div class=attorna-mobile-header-wrap>
        <div class="attorna-mobile-header attorna-header-background attorna-style-slide attorna-sticky-mobile-navigation "
            id=attorna-mobile-header>
            <div class="attorna-mobile-header-container attorna-container clearfix">
                <div class="attorna-logo  attorna-item-pdlr">
                    <div class=attorna-logo-inner>
                        <a class
                            href=<?=Com_Helper_Url::getInstance()->urlBase;?>/es/page/index.html><?php Gallery_Widget_Clientes::getInstance()->setLan($this->lan)->setType("LogoMobile")->renderLogoMenu();?></a>
                    </div>
                </div>
                <div class=attorna-mobile-menu-right>

                    <div class=attorna-top-search-wrap>
                        <div class=attorna-top-search-close></div>
                        <div class=attorna-top-search-row>
                            <div class=attorna-top-search-cell>
                                <form role=search method=get class=search-form action=#>
                                    <input type=text class="search-field attorna-title-font" placeholder=Search... value
                                        name=s>
                                    <div class=attorna-top-search-submit><i class="fa fa-search"></i></div>
                                    <input type=submit class=search-submit value=Search>
                                    <div class=attorna-top-search-close><i class=icon_close></i></div>
                                </form>
                            </div>
                        </div>
                    </div>

                    <div class=attorna-mobile-menu><a
                            class="attorna-mm-menu-button attorna-mobile-menu-button attorna-mobile-button-hamburger-with-border"
                            href=#attorna-mobile-menu><i class="fa fa-bars"></i></a>
                        <div class="attorna-mm-menu-wrap attorna-navigation-font" id=attorna-mobile-menu
                            data-slide=right>
                            <ul id=menu-main-navigation class=m-menu>
                                <?php Menu_Widget_Menu::getInstance()->setLan($this->lan)->setParent(1)->render();?>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="attorna-body-outer-wrapper ">
        <div class="attorna-body-wrapper clearfix  attorna-with-frame">
            <div class="attorna-logo  attorna-item-pdlr sectionBigLogo">
                <div class=attorna-logo-inner style="margin: auto;">
                    <a class
                        href=index.html><?php Gallery_Widget_Clientes::getInstance()->setLan($this->lan)->setType("LogoMenu")->renderLogoMenu();?></a>
                </div>
            </div>
            <header
                class="attorna-header-wrap attorna-header-style-plain  attorna-style-menu-right attorna-sticky-navigation attorna-style-fixed"
                data-navigation-offset=75px>
                <div class=attorna-header-background></div>
                <div class="attorna-header-container  attorna-container">
                    <div class="attorna-header-container-inner clearfix">

                        <div class="attorna-navigation attorna-item-pdlr clearfix"
                            style="width: 100%;text-align: center;">
                            <div class=attorna-main-menu id=attorna-main-menu>
                                <ul id=menu-main-navigation-1 class=sf-menu>
                                    <?php Menu_Widget_Menu::getInstance()->setLan($this->lan)->setParent(1)->render();?>
                                </ul>
                                <div class=attorna-navigation-slide-bar id=attorna-navigation-slide-bar></div>
                            </div>
                            <div class="attorna-main-menu-right-wrap clearfix ">

                            </div>
                        </div>
                    </div>
                </div>
            </header>

            <div class=attorna-page-wrapper id=attorna-page-wrapper>
                <div class=gdlr-core-page-builder-body>
                    <div class="gdlr-core-pbf-wrapper " style="padding: 85px 0px 60px 0px;">
                        <div class=gdlr-core-pbf-background-wrap></div>
                        <div class="gdlr-core-pbf-wrapper-content gdlr-core-js ">
                            <div class="gdlr-core-pbf-wrapper-container clearfix gdlr-core-container">
                                <div class="gdlr-core-pbf-column gdlr-core-column-20 gdlr-core-column-first">
                                    <div class="gdlr-core-pbf-column-content-margin gdlr-core-js "
                                        style="padding: 0px 0px 0px 0px;">
                                        <div class="gdlr-core-pbf-column-content clearfix gdlr-core-js ">
                                            <div class=gdlr-core-pbf-element>
                                                <div class="gdlr-core-image-item gdlr-core-item-pdlr gdlr-core-item-pdb  gdlr-core-center-align"
                                                    style="padding-bottom: 0px ;">
                                                    <div class="gdlr-core-image-item-wrap gdlr-core-media-image  gdlr-core-image-item-style-round"
                                                        style="border-width: 0px;margin: 0px 0px 37px 0px;"><img
                                                            src="https://demo.goodlayers.com/attorna/wp-content/uploads/2019/02/Emma2.jpg"
                                                            alt width=599 height=551 title=James></div>
                                                </div>
                                            </div>
                                            <div class=gdlr-core-pbf-element>
                                                <div class="gdlr-core-title-item gdlr-core-item-pdb clearfix  gdlr-core-left-align gdlr-core-title-item-caption-bottom gdlr-core-item-pdlr"
                                                    style="padding-bottom: 25px ;">
                                                    <div class="gdlr-core-title-item-title-wrap ">
                                                        <h3 class="gdlr-core-title-item-title gdlr-core-skin-title "
                                                            style="font-size: 22px ;font-weight: 700 ;letter-spacing: 0px ;text-transform: none ;">
                                                            James Milner<span
                                                                class="gdlr-core-title-item-title-divider gdlr-core-skin-divider"></span>
                                                        </h3>
                                                    </div><span
                                                        class="gdlr-core-title-item-caption gdlr-core-info-font gdlr-core-skin-caption"
                                                        style="font-style: normal ;margin-top: 5px ;">Partner</span>
                                                </div>
                                            </div>
                                            <div class=gdlr-core-pbf-element>
                                                <div class="gdlr-core-text-box-item gdlr-core-item-pdlr gdlr-core-item-pdb gdlr-core-left-align gdlr-core-no-p-space"
                                                    style="padding-bottom: 10px ;">
                                                    <div class=gdlr-core-text-box-item-content
                                                        style="font-size: 16px ;text-transform: none ;color: #323232 ;">
                                                        <p><span
                                                                style="font-weight: bold; margin-right: 10px;">Email</span>
                                                            Contact@Attornasite.co</p>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class=gdlr-core-pbf-element>
                                                <div class="gdlr-core-text-box-item gdlr-core-item-pdlr gdlr-core-item-pdb gdlr-core-left-align"
                                                    style="padding-bottom: 0px ;">
                                                    <div class=gdlr-core-text-box-item-content
                                                        style="font-size: 16px ;text-transform: none ;color: #323232 ;">
                                                        <p><span
                                                                style="font-weight: bold; margin-right: 10px;">Phone</span>
                                                            +1-2454-2345-22</p>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class=gdlr-core-pbf-element>
                                                <div
                                                    class="gdlr-core-social-network-item gdlr-core-item-pdb  gdlr-core-left-align gdlr-core-item-pdlr">
                                                    <a href=# target=_blank class=gdlr-core-social-network-icon
                                                        title=facebook style="font-size: 18px ;"><i
                                                            class="fa fa-facebook"></i></a><a href=# target=_blank
                                                        class=gdlr-core-social-network-icon title=linkedin
                                                        style="font-size: 18px ;margin-left: 16px ;"><i
                                                            class="fa fa-linkedin"></i></a><a href=# target=_blank
                                                        class=gdlr-core-social-network-icon title=pinterest
                                                        style="font-size: 18px ;margin-left: 16px ;"><i
                                                            class="fa fa-pinterest-p"></i></a><a href=# target=_blank
                                                        class=gdlr-core-social-network-icon title=twitter
                                                        style="font-size: 18px ;margin-left: 16px ;"><i
                                                            class="fa fa-twitter"></i></a><a href=# target=_blank
                                                        class=gdlr-core-social-network-icon title=instagram
                                                        style="font-size: 18px ;margin-left: 16px ;"><i
                                                            class="fa fa-instagram"></i></a></div>
                                            </div>
                                            <div class=gdlr-core-pbf-element>
                                                <div
                                                    class="gdlr-core-button-item gdlr-core-item-pdlr gdlr-core-item-pdb gdlr-core-left-align">
                                                    <a class="gdlr-core-button  gdlr-core-button-transparent gdlr-core-button-no-border"
                                                        href=#
                                                        style="font-size: 12px ;font-weight: 600 ;letter-spacing: 3px ;color: #b1976b ;padding: 0px 0px 0px 0px;"><span
                                                            class=gdlr-core-content>Download VCard</span><i
                                                            class="gdlr-core-pos-right fa fa-long-arrow-right"
                                                            style="font-size: 18px ;color: #b1976b ;"></i></a></div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="gdlr-core-pbf-column gdlr-core-column-40">
                                    <div class="gdlr-core-pbf-column-content-margin gdlr-core-js "
                                        style="padding: 0px 0px 0px 0px;">
                                        <div class="gdlr-core-pbf-column-content clearfix gdlr-core-js ">
                                            <div class=gdlr-core-pbf-element>
                                                <div class="gdlr-core-title-item gdlr-core-item-pdb clearfix  gdlr-core-left-align gdlr-core-title-item-caption-bottom gdlr-core-item-pdlr"
                                                    style="padding-bottom: 25px ;">
                                                    <div class="gdlr-core-title-item-title-wrap ">
                                                        <h2 class="gdlr-core-title-item-title gdlr-core-skin-title "
                                                            style="font-size: 15px ;font-weight: 700 ;letter-spacing: 4px ;">
                                                            Biography<span
                                                                class="gdlr-core-title-item-title-divider gdlr-core-skin-divider"></span>
                                                        </h2>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class=gdlr-core-pbf-element>
                                                <div class="gdlr-core-text-box-item gdlr-core-item-pdlr gdlr-core-item-pdb gdlr-core-left-align"
                                                    style="padding-bottom: 0px ;">
                                                    <div class=gdlr-core-text-box-item-content
                                                        style="text-transform: none ;">
                                                        <p>John Smith is a Partner at Attorna and the Head of
                                                            International Arbitration Practice. John specialises in
                                                            consulting clients in the area of international trade, and
                                                            representing their interests in international commercial
                                                            arbitrations of GAFTA.</p>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class=gdlr-core-pbf-element>
                                                <div class="gdlr-core-divider-item gdlr-core-divider-item-normal gdlr-core-item-pdlr gdlr-core-left-align"
                                                    style="margin-bottom: 20px ;">
                                                    <div class=gdlr-core-divider-container style="max-width: 22px ;">
                                                        <div class="gdlr-core-divider-line gdlr-core-skin-divider"
                                                            style="border-color: #b1976b ;border-bottom-width: 2px ;">
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class=gdlr-core-pbf-element>
                                                <div class="gdlr-core-text-box-item gdlr-core-item-pdlr gdlr-core-item-pdb gdlr-core-left-align"
                                                    style="padding-bottom: 0px ;">
                                                    <div class=gdlr-core-text-box-item-content
                                                        style="font-size: 16px ;text-transform: none ;">
                                                        <p>John is the leader of the Working Group on International
                                                            Taxation &#038; EU Harmonization in UK at the American
                                                            Chamber of Commerce. He is also the Committee Head of the
                                                            Permanent Scientific Committee of IFA. During 2011 John
                                                            served as the Co-Chair of the Tax Committee of the American
                                                            Chamber of Commerce and was the member of the working group
                                                            on VAT reform at the Ministry of Finance of United Kingdom.
                                                        </p>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class=gdlr-core-pbf-element>
                                                <div class="gdlr-core-divider-item gdlr-core-divider-item-normal gdlr-core-item-pdlr gdlr-core-left-align"
                                                    style="margin-bottom: 20px ;">
                                                    <div class=gdlr-core-divider-container style="max-width: 22px ;">
                                                        <div class="gdlr-core-divider-line gdlr-core-skin-divider"
                                                            style="border-color: #b1976b ;border-bottom-width: 2px ;">
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class=gdlr-core-pbf-element>
                                                <div class="gdlr-core-text-box-item gdlr-core-item-pdlr gdlr-core-item-pdb gdlr-core-left-align"
                                                    style="padding-bottom: 20px ;">
                                                    <div class=gdlr-core-text-box-item-content
                                                        style="font-size: 16px ;text-transform: none ;">
                                                        <p>Prior to joining Attorna, John worked in the UK of an
                                                            international law firm.</p>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class=gdlr-core-pbf-element>
                                                <div class="gdlr-core-title-item gdlr-core-item-pdb clearfix  gdlr-core-left-align gdlr-core-title-item-caption-top gdlr-core-item-pdlr"
                                                    style="padding-bottom: 20px ;">
                                                    <div class="gdlr-core-title-item-title-wrap ">
                                                        <h3 class="gdlr-core-title-item-title gdlr-core-skin-title "
                                                            style="font-size: 15px ;font-weight: 700 ;letter-spacing: 4px ;">
                                                            Pratice Areas<span
                                                                class="gdlr-core-title-item-title-divider gdlr-core-skin-divider"></span>
                                                        </h3>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class=gdlr-core-pbf-element>
                                                <div
                                                    class="gdlr-core-icon-list-item gdlr-core-item-pdlr gdlr-core-item-pdb clearfix  gdlr-core-left-align">
                                                    <ul>
                                                        <li class=" gdlr-core-skin-divider"
                                                            style="margin-bottom: 8px ;"><span
                                                                class=gdlr-core-icon-list-icon-wrap
                                                                style="margin-top: 5px ;margin-right: 12px ;"><i
                                                                    class="gdlr-core-icon-list-icon fa fa-dot-circle-o"
                                                                    style="color: #b1976b ;font-size: 13px ;width: 13px ;"></i></span>
                                                            <div class=gdlr-core-icon-list-content-wrap><span
                                                                    class=gdlr-core-icon-list-content
                                                                    style="color: #b1976b ;font-size: 16px ;">Estate
                                                                    Planning</span></div>
                                                        </li>
                                                        <li class=" gdlr-core-skin-divider"
                                                            style="margin-bottom: 8px ;"><span
                                                                class=gdlr-core-icon-list-icon-wrap
                                                                style="margin-top: 5px ;margin-right: 12px ;"><i
                                                                    class="gdlr-core-icon-list-icon fa fa-dot-circle-o"
                                                                    style="color: #b1976b ;font-size: 13px ;width: 13px ;"></i></span>
                                                            <div class=gdlr-core-icon-list-content-wrap><span
                                                                    class=gdlr-core-icon-list-content
                                                                    style="color: #b1976b ;font-size: 16px ;">Business
                                                                    and Corporate Law</span></div>
                                                        </li>
                                                        <li class=" gdlr-core-skin-divider"
                                                            style="margin-bottom: 8px ;"><span
                                                                class=gdlr-core-icon-list-icon-wrap
                                                                style="margin-top: 5px ;margin-right: 12px ;"><i
                                                                    class="gdlr-core-icon-list-icon fa fa-dot-circle-o"
                                                                    style="color: #b1976b ;font-size: 13px ;width: 13px ;"></i></span>
                                                            <div class=gdlr-core-icon-list-content-wrap><span
                                                                    class=gdlr-core-icon-list-content
                                                                    style="color: #b1976b ;font-size: 16px ;">Contract
                                                                    Law</span></div>
                                                        </li>
                                                        <li class=" gdlr-core-skin-divider"
                                                            style="margin-bottom: 8px ;"><span
                                                                class=gdlr-core-icon-list-icon-wrap
                                                                style="margin-top: 5px ;margin-right: 12px ;"><i
                                                                    class="gdlr-core-icon-list-icon fa fa-dot-circle-o"
                                                                    style="color: #b1976b ;font-size: 13px ;width: 13px ;"></i></span>
                                                            <div class=gdlr-core-icon-list-content-wrap><span
                                                                    class=gdlr-core-icon-list-content
                                                                    style="color: #b1976b ;font-size: 16px ;">Real
                                                                    Estate Law</span></div>
                                                        </li>
                                                    </ul>
                                                </div>
                                            </div>
                                            <div class=gdlr-core-pbf-element>
                                                <div class="gdlr-core-divider-item gdlr-core-divider-item-normal gdlr-core-item-pdlr gdlr-core-center-align"
                                                    style="margin-bottom: 45px ;">
                                                    <div class="gdlr-core-divider-line gdlr-core-skin-divider"></div>
                                                </div>
                                            </div>
                                            <div class=gdlr-core-pbf-element>
                                                <div
                                                    class="gdlr-core-title-item gdlr-core-item-pdb clearfix  gdlr-core-left-align gdlr-core-title-item-caption-top gdlr-core-item-pdlr">
                                                    <div class="gdlr-core-title-item-title-wrap ">
                                                        <h3 class="gdlr-core-title-item-title gdlr-core-skin-title "
                                                            style="font-size: 15px ;font-weight: 700 ;letter-spacing: 4px ;">
                                                            Education & Bar Admission<span
                                                                class="gdlr-core-title-item-title-divider gdlr-core-skin-divider"></span>
                                                        </h3>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class=gdlr-core-pbf-element>
                                                <div class="gdlr-core-text-box-item gdlr-core-item-pdlr gdlr-core-item-pdb gdlr-core-left-align"
                                                    style="padding-bottom: 0px ;">
                                                    <div class=gdlr-core-text-box-item-content
                                                        style="font-size: 16px ;text-transform: none ;">
                                                        <p>BA, Columbia College; 2001</p>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class=gdlr-core-pbf-element>
                                                <div class="gdlr-core-divider-item gdlr-core-divider-item-normal gdlr-core-item-pdlr gdlr-core-left-align"
                                                    style="margin-bottom: 20px ;">
                                                    <div class=gdlr-core-divider-container style="max-width: 22px ;">
                                                        <div class="gdlr-core-divider-line gdlr-core-skin-divider"
                                                            style="border-color: #b1976b ;border-bottom-width: 2px ;">
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class=gdlr-core-pbf-element>
                                                <div class="gdlr-core-text-box-item gdlr-core-item-pdlr gdlr-core-item-pdb gdlr-core-left-align"
                                                    style="padding-bottom: 0px ;">
                                                    <div class=gdlr-core-text-box-item-content
                                                        style="font-size: 16px ;text-transform: none ;">
                                                        <p>Master of Law, 2007. UK University</p>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class=gdlr-core-pbf-element>
                                                <div class="gdlr-core-divider-item gdlr-core-divider-item-normal gdlr-core-item-pdlr gdlr-core-left-align"
                                                    style="margin-bottom: 20px ;">
                                                    <div class=gdlr-core-divider-container style="max-width: 22px ;">
                                                        <div class="gdlr-core-divider-line gdlr-core-skin-divider"
                                                            style="border-color: #b1976b ;border-bottom-width: 2px ;">
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class=gdlr-core-pbf-element>
                                                <div class="gdlr-core-text-box-item gdlr-core-item-pdlr gdlr-core-item-pdb gdlr-core-left-align"
                                                    style="padding-bottom: 0px ;">
                                                    <div class=gdlr-core-text-box-item-content
                                                        style="font-size: 16px ;text-transform: none ;">
                                                        <p>Admitted to the Bar since 2013</p>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class=gdlr-core-pbf-element>
                                                <div class="gdlr-core-divider-item gdlr-core-divider-item-normal gdlr-core-item-pdlr gdlr-core-left-align"
                                                    style="margin-bottom: 20px ;">
                                                    <div class=gdlr-core-divider-container style="max-width: 22px ;">
                                                        <div class="gdlr-core-divider-line gdlr-core-skin-divider"
                                                            style="border-color: #b1976b ;border-bottom-width: 2px ;">
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class=gdlr-core-pbf-element>
                                                <div class="gdlr-core-text-box-item gdlr-core-item-pdlr gdlr-core-item-pdb gdlr-core-left-align"
                                                    style="padding-bottom: 0px ;">
                                                    <div class=gdlr-core-text-box-item-content
                                                        style="font-size: 16px ;text-transform: none ;">
                                                        <p>Member of the International Bar Association</p>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class=gdlr-core-pbf-element>
                                                <div class="gdlr-core-divider-item gdlr-core-divider-item-normal gdlr-core-item-pdlr gdlr-core-left-align"
                                                    style="margin-bottom: 20px ;">
                                                    <div class=gdlr-core-divider-container style="max-width: 22px ;">
                                                        <div class="gdlr-core-divider-line gdlr-core-skin-divider"
                                                            style="border-color: #b1976b ;border-bottom-width: 2px ;">
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class=gdlr-core-pbf-element>
                                                <div class="gdlr-core-text-box-item gdlr-core-item-pdlr gdlr-core-item-pdb gdlr-core-left-align"
                                                    style="padding-bottom: 0px ;">
                                                    <div class=gdlr-core-text-box-item-content
                                                        style="font-size: 16px ;text-transform: none ;">
                                                        <p>Member of the London City Bar Association</p>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class=gdlr-core-pbf-element>
                                                <div class="gdlr-core-divider-item gdlr-core-divider-item-normal gdlr-core-item-pdlr gdlr-core-left-align"
                                                    style="margin-bottom: 20px ;">
                                                    <div class=gdlr-core-divider-container style="max-width: 22px ;">
                                                        <div class="gdlr-core-divider-line gdlr-core-skin-divider"
                                                            style="border-color: #b1976b ;border-bottom-width: 2px ;">
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class=gdlr-core-pbf-element>
                                                <div class="gdlr-core-text-box-item gdlr-core-item-pdlr gdlr-core-item-pdb gdlr-core-left-align"
                                                    style="padding-bottom: 20px ;">
                                                    <div class=gdlr-core-text-box-item-content
                                                        style="font-size: 16px ;text-transform: none ;">
                                                        <p>Speaker of GAFTA Professional Development Programmes</p>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class=gdlr-core-pbf-element>
                                                <div class="gdlr-core-divider-item gdlr-core-divider-item-normal gdlr-core-item-pdlr gdlr-core-center-align"
                                                    style="margin-bottom: 45px ;">
                                                    <div class="gdlr-core-divider-line gdlr-core-skin-divider"></div>
                                                </div>
                                            </div>
                                            <div class=gdlr-core-pbf-element>
                                                <div
                                                    class="gdlr-core-title-item gdlr-core-item-pdb clearfix  gdlr-core-left-align gdlr-core-title-item-caption-top gdlr-core-item-pdlr">
                                                    <div class="gdlr-core-title-item-title-wrap ">
                                                        <h3 class="gdlr-core-title-item-title gdlr-core-skin-title "
                                                            style="font-size: 15px ;font-weight: 700 ;letter-spacing: 4px ;">
                                                            Pratice Areas<span
                                                                class="gdlr-core-title-item-title-divider gdlr-core-skin-divider"></span>
                                                        </h3>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class=gdlr-core-pbf-element>
                                                <div class="gdlr-core-text-box-item gdlr-core-item-pdlr gdlr-core-item-pdb gdlr-core-left-align"
                                                    style="padding-bottom: 0px ;">
                                                    <div class=gdlr-core-text-box-item-content
                                                        style="font-size: 16px ;text-transform: none ;">
                                                        <p>Leading lawyer in London for Dispute Resolution</p>
                                                        <p><strong>The Legal500 (2015 &#8211; 2018)</strong></p>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class=gdlr-core-pbf-element>
                                                <div class="gdlr-core-divider-item gdlr-core-divider-item-normal gdlr-core-item-pdlr gdlr-core-left-align"
                                                    style="margin-bottom: 20px ;">
                                                    <div class=gdlr-core-divider-container style="max-width: 22px ;">
                                                        <div class="gdlr-core-divider-line gdlr-core-skin-divider"
                                                            style="border-color: #b1976b ;border-bottom-width: 2px ;">
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class=gdlr-core-pbf-element>
                                                <div class="gdlr-core-text-box-item gdlr-core-item-pdlr gdlr-core-item-pdb gdlr-core-left-align"
                                                    style="padding-bottom: 0px ;">
                                                    <div class=gdlr-core-text-box-item-content
                                                        style="font-size: 16px ;text-transform: none ;">
                                                        <p>Leading lawyer in London for Family law</p>
                                                        <p><strong>Legal Awards 2016</strong></p>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class=gdlr-core-pbf-element>
                                                <div class="gdlr-core-divider-item gdlr-core-divider-item-normal gdlr-core-item-pdlr gdlr-core-left-align"
                                                    style="margin-bottom: 20px ;">
                                                    <div class=gdlr-core-divider-container style="max-width: 22px ;">
                                                        <div class="gdlr-core-divider-line gdlr-core-skin-divider"
                                                            style="border-color: #b1976b ;border-bottom-width: 2px ;">
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class=gdlr-core-pbf-element>
                                                <div class="gdlr-core-text-box-item gdlr-core-item-pdlr gdlr-core-item-pdb gdlr-core-left-align"
                                                    style="padding-bottom: 0px ;">
                                                    <div class=gdlr-core-text-box-item-content
                                                        style="font-size: 16px ;text-transform: none ;">
                                                        <p>The best team in London for International Trade</p>
                                                        <p><strong>Legal Awards 2018</strong></p>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class=gdlr-core-pbf-element>
                                                <div class="gdlr-core-divider-item gdlr-core-divider-item-normal gdlr-core-item-pdlr gdlr-core-left-align"
                                                    style="margin-bottom: 20px ;">
                                                    <div class=gdlr-core-divider-container style="max-width: 22px ;">
                                                        <div class="gdlr-core-divider-line gdlr-core-skin-divider"
                                                            style="border-color: #b1976b ;border-bottom-width: 2px ;">
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class=gdlr-core-pbf-element>
                                                <div class="gdlr-core-text-box-item gdlr-core-item-pdlr gdlr-core-item-pdb gdlr-core-left-align"
                                                    style="padding-bottom: 20px ;">
                                                    <div class=gdlr-core-text-box-item-content
                                                        style="font-size: 16px ;text-transform: none ;">
                                                        <p>Leading lawyer in London for Private clients practice The</p>
                                                        <p><strong>Legal500 2018</strong></p>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class=gdlr-core-pbf-element>
                                                <div class="gdlr-core-divider-item gdlr-core-divider-item-normal gdlr-core-item-pdlr gdlr-core-center-align"
                                                    style="margin-bottom: 45px ;">
                                                    <div class="gdlr-core-divider-line gdlr-core-skin-divider"></div>
                                                </div>
                                            </div>
                                            <div class=gdlr-core-pbf-element>
                                                <div class="gdlr-core-title-item gdlr-core-item-pdb clearfix  gdlr-core-left-align gdlr-core-title-item-caption-bottom gdlr-core-item-pdlr"
                                                    style="padding-bottom: 45px ;">
                                                    <div class="gdlr-core-title-item-title-wrap ">
                                                        <h3 class="gdlr-core-title-item-title gdlr-core-skin-title "
                                                            style="font-size: 15px ;font-weight: 700 ;letter-spacing: 4px ;">
                                                            My Skills<span
                                                                class="gdlr-core-title-item-title-divider gdlr-core-skin-divider"></span>
                                                        </h3>
                                                    </div><span
                                                        class="gdlr-core-title-item-caption gdlr-core-info-font gdlr-core-skin-caption"
                                                        style="font-style: normal ;">One morning, when Gregor Samsa woke
                                                        from troubled dreams, he found himself transformed in his bed
                                                        into</span>
                                                </div>
                                            </div>
                                            <div class=gdlr-core-pbf-element>
                                                <div
                                                    class="gdlr-core-skill-bar-item gdlr-core-item-pdlr gdlr-core-item-pdb  gdlr-core-size-small gdlr-core-type-round">
                                                    <div class=gdlr-core-skill-bar>
                                                        <div class="gdlr-core-skill-bar-head gdlr-core-title-font"><span
                                                                class=gdlr-core-skill-bar-title>Practice
                                                                Area</span><span class=gdlr-core-skill-bar-right
                                                                style="color: #000000 ;">80%</span></div>
                                                        <div class=gdlr-core-skill-bar-progress>
                                                            <div class="gdlr-core-skill-bar-filled gdlr-core-js"
                                                                data-width=80 style="background-color: #8a7552 ;"></div>
                                                        </div>
                                                    </div>
                                                    <div class=gdlr-core-skill-bar>
                                                        <div class="gdlr-core-skill-bar-head gdlr-core-title-font"><span
                                                                class=gdlr-core-skill-bar-title>Happy
                                                                Customer</span><span class=gdlr-core-skill-bar-right
                                                                style="color: #000000 ;">100%</span></div>
                                                        <div class=gdlr-core-skill-bar-progress>
                                                            <div class="gdlr-core-skill-bar-filled gdlr-core-js"
                                                                data-width=100 style="background-color: #8a7552 ;">
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div class=gdlr-core-skill-bar>
                                                        <div class="gdlr-core-skill-bar-head gdlr-core-title-font"><span
                                                                class=gdlr-core-skill-bar-title>Firm Size</span><span
                                                                class=gdlr-core-skill-bar-right
                                                                style="color: #000000 ;">70%</span></div>
                                                        <div class=gdlr-core-skill-bar-progress>
                                                            <div class="gdlr-core-skill-bar-filled gdlr-core-js"
                                                                data-width=70 style="background-color: #8a7552 ;"></div>
                                                        </div>
                                                    </div>
                                                    <div class=gdlr-core-skill-bar>
                                                        <div class="gdlr-core-skill-bar-head gdlr-core-title-font"><span
                                                                class=gdlr-core-skill-bar-title>Success Case</span><span
                                                                class=gdlr-core-skill-bar-right
                                                                style="color: #000000 ;">90%</span></div>
                                                        <div class=gdlr-core-skill-bar-progress>
                                                            <div class="gdlr-core-skill-bar-filled gdlr-core-js"
                                                                data-width=90 style="background-color: #8a7552 ;"></div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <footer>
                <div class="attorna-footer-wrapper ">
                    <div class="attorna-footer-container attorna-container clearfix">
                        <div class="attorna-footer-column attorna-item-pdlr attorna-column-20">
                            <div id=text-1 class="widget widget_text attorna-widget">
                                <div class=textwidget>
                                    <p><?php Gallery_Widget_Clientes::getInstance()->setLan($this->lan)->setType("LogoFooter")->renderLogoFooter();?>
                                        <br> <span class=gdlr-core-space-shortcode style="margin-top: -27px ;"></span>
                                        <br>
                                        <!-- <?=Texts_Helper_Text::getInstance()->get($this->lan, "FooterResume")->TxtDescription;?> -->
                                    </p>

                                </div>
                            </div>
                        </div>
                        <div class="attorna-footer-column attorna-item-pdlr attorna-column-20">
                            <div id=text-7 class="widget widget_text attorna-widget">
                                <h3 class="attorna-widget-title">
                                    <?=Texts_Helper_Text::getInstance()->get($this->lan, "FooterTitleContact")->TxtDescription;?>
                                </h3><span class=clear></span>
                                <div class=textwidget>
                                    <p><?=Texts_Helper_Text::getInstance()->get($this->lan, "ContactAddress")->TxtDescription;?>
                                    </p>
                                    <p><span
                                            style="color: #fff;"><?=Texts_Helper_Text::getInstance()->get($this->lan, "ContactPhone")->TxtDescription;?></span>
                                        <br> <span
                                            style="color: #545d66;"><?=Texts_Helper_Text::getInstance()->get($this->lan, "ContactEmail")->TxtDescription;?></span>
                                    </p>
                                    <div class="gdlr-core-social-network-item gdlr-core-item-pdb  gdlr-core-none-align"
                                        style="padding-bottom: 0px ;">
                                        <a href="<?=Texts_Helper_Text::getInstance()->get($this->lan, "linkedinUrl")->TxtDescription;?>"
                                            target=_blank class=gdlr-core-social-network-icon title=linkedin
                                            style="font-size: 16px ;color: #545d66 ;"><i class="fa fa-linkedin"></i></a>
                                        <a href="<?=Texts_Helper_Text::getInstance()->get($this->lan, "twitterUrl")->TxtDescription;?>"
                                            target=_blank class=gdlr-core-social-network-icon title=twitter
                                            style="font-size: 16px ;color: #545d66 ;"><i class="fa fa-twitter"></i></a>

                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="attorna-footer-column attorna-item-pdlr attorna-column-20">
                            <div id=gdlr-core-custom-menu-widget-4
                                class="widget widget_gdlr-core-custom-menu-widget attorna-widget">
                                <h3 class="attorna-widget-title">
                                    <?=Texts_Helper_Text::getInstance()->get($this->lan, "FooterTitlePracticeAreas")->TxtDescription;?>
                                </h3><span class=clear></span>
                                <div class=menu-practice-areas-container>
                                    <?php Services_Widget_ServicesMenu::getInstance()->setLan($this->lan)->setParent(18)->render();?>

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class=attorna-copyright-wrapper>
                    <div class="attorna-copyright-container attorna-container clearfix">
                        <div class="attorna-copyright-left attorna-item-pdlr">
                            <?=Texts_Helper_Text::getInstance()->get($this->lan, "Copyright")->TxtDescription;?></div>
                        <div class="attorna-copyright-right attorna-item-pdlr">
                            <?php Menu_Widget_MenuFooter::getInstance()->setLan($this->lan)->setParent(18)->render();?>

                        </div>
                    </div>
                </div>
            </footer>
        </div>
    </div>

    <script src='<?=Com_Helper_Url::getInstance()->urlBase;?>/Resources/Script/Public/jquery/jquery.js'></script>
    <script src='<?=Com_Helper_Url::getInstance()->urlBase;?>/Resources/Script/Public/jquery/jquery-migrate.min.js'>
    </script>
    <script
        src='<?=Com_Helper_Url::getInstance()->urlBase;?>/Resources/Script/Public/plugins/revslider/public/assets/js/jquery.themepunch.tools.min.js'>
    </script>
    <script
        src='<?=Com_Helper_Url::getInstance()->urlBase;?>/Resources/Script/Public/plugins/revslider/public/assets/js/jquery.themepunch.revolution.min.js'>
    </script>
    <script
        src="<?=Com_Helper_Url::getInstance()->urlBase;?>/Resources/Script/Public/plugins/revslider/public/assets/js/extensions/revolution.extension.slideanims.min.js">
    </script>
    <script
        src="<?=Com_Helper_Url::getInstance()->urlBase;?>/Resources/Script/Public/plugins/revslider/public/assets/js/extensions/revolution.extension.layeranimation.min.js">
    </script>
    <script
        src="<?=Com_Helper_Url::getInstance()->urlBase;?>/Resources/Script/Public/plugins/revslider/public/assets/js/extensions/revolution.extension.kenburn.min.js">
    </script>
    <script
        src="<?=Com_Helper_Url::getInstance()->urlBase;?>/Resources/Script/Public/plugins/revslider/public/assets/js/extensions/revolution.extension.navigation.min.js">
    </script>
    <script
        src="<?=Com_Helper_Url::getInstance()->urlBase;?>/Resources/Script/Public/plugins/revslider/public/assets/js/extensions/revolution.extension.parallax.min.js">
    </script>
    <script
        src="<?=Com_Helper_Url::getInstance()->urlBase;?>/Resources/Script/Public/plugins/revslider/public/assets/js/extensions/revolution.extension.actions.min.js">
    </script>
    <script
        src="<?=Com_Helper_Url::getInstance()->urlBase;?>/Resources/Script/Public/plugins/revslider/public/assets/js/extensions/revolution.extension.video.min.js">
    </script>

    <script
        src='<?=Com_Helper_Url::getInstance()->urlBase;?>/Resources/Script/Public/plugins/goodlayers-core/plugins/combine/script.js'>
    </script>
    <script>
    var gdlr_core_pbf = {
        "admin": "",
        "video": {
            "width": "640",
            "height": "360"
        },
        "ajax_url": "https:\/\/demo.goodlayers.com\/attorna\/wp-admin\/admin-ajax.php"
    };
    </script>
    <script
        src='<?=Com_Helper_Url::getInstance()->urlBase;?>/Resources/Script/Public/plugins/goodlayers-core/include/js/page-builder.js'>
    </script>


    <script src='<?=Com_Helper_Url::getInstance()->urlBase;?>/Resources/Script/Public/jquery/ui/effect.min.js'></script>
    <script src='<?=Com_Helper_Url::getInstance()->urlBase;?>/Resources/Script/Public/jquery.mmenu.js'></script>
    <script src='<?=Com_Helper_Url::getInstance()->urlBase;?>/Resources/Script/Public/jquery.superfish.js'></script>
    <script src='<?=Com_Helper_Url::getInstance()->urlBase;?>/Resources/Script/Public/script-core.js'></script>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-173265186-1"></script>
    <script>
    window.dataLayer = window.dataLayer || [];

    function gtag() {
        dataLayer.push(arguments);
    }
    gtag('js', new Date());

    gtag('config', 'UA-173265186-1');
    </script>


</body>

</html>